defaults:
  - backend: onnxruntime # default backend
  - launcher: torchrun # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: onnxruntime_llama

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: meta-llama/Llama-2-7b-hf

launcher:
  device_isolation: true
  nproc_per_node: 4

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 1000

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
